grafana:
  enabled: true
  adminPassword: admin123
  persistence:
    enabled: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 30m
    retentionSize: 256MB
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
