{{- if .Values.seed.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-data
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: seed
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: {{ .Values.seed.ttlSecondsAfterFinished }}
  activeDeadlineSeconds: {{ .Values.seed.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: seed
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: seed
          image: "{{ .Values.seed.image.repository }}:{{ .Values.seed.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: VOTE_URL
              value: {{ .Values.seed.voteUrl | quote }}
            - name: POSTGRES_HOST
              value: {{ include "voting-app.postgresqlServiceName" . | quote }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "voting-app.postgresqlSecretName" . | quote }}
                  key: {{ include "voting-app.postgresqlUserPasswordKey" . | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
{{- end }}
