apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "voting-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "voting-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"

          env:
            - name: REDIS_HOST
              value: voting-app-redis-master
            - name: POSTGRES_HOST
              value: voting-app-postgresql
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.auth.password | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}

            # .NET runtime configuration
            - name: DOTNET_GC_SERVER
              value: "1"
            - name: DOTNET_GC_HEAP_HARD_LIMIT
              value: "800000000"

          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}

          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}

          volumeMounts:
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: tmp
          emptyDir: {}
